modLoader="javafml"
loaderVersion="[47,)"
license="GNU Lesser General Public License version 2.1 (LGPLv2.1)"

[[mods]]
modId="simply_blast_furnace_recipes"
version="1.0.0"
displayName="Simply Blast Furnace Recipes"
credits="Azureddraig"
displayURL="https://discord.gg/GTgx6tYjg2"
authors="Azureddraig"
description="Expand the Furnace recipes to work in a blast furnace"

[[dependencies.simply_blast_furnace_recipes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




